FROM node:20-alpine
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --legacy-peer-deps --ignore-scripts
COPY prisma ./prisma
RUN npx prisma generate
ENV PORT=3003
ENV HOSTNAME=0.0.0.0
EXPOSE 3003
CMD ["npm", "run", "dev", "--", "-p", "3003"]
